 services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: esl_db
      POSTGRES_USER: esl_user
      POSTGRES_PASSWORD: 1234
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U esl_user -d esl_db -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./backend/.env

    environment:
      DB_NAME: esl_db
      DB_USER: esl_user
      DB_PASSWORD: 1234
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DEBUG: "False"
    volumes:
      - static_volume:/app/staticfiles

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:3000"
volumes:
  db_data:
  static_volume:
