# Generated by Django 5.1.4 on 2024-12-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronunciation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronunciationexercise',
            name='level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='A1', max_length=15),
        ),
    ]
