# Generated by Django 5.1.4 on 2024-12-29 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pronunciation', '0003_mispronouncedwordglobal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MispronouncedWordGlobal',
        ),
    ]
