# Generated by Django 5.1.4 on 2024-12-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_voiceconversation_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicemessage',
            name='is_feedback',
        ),
    ]
