# Generated by Django 5.1.4 on 2024-12-29 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_remove_voicemessage_is_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceconversation',
            name='topic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='voiceconversation',
            unique_together={('user', 'topic')},
        ),
    ]
