# Generated by Django 5.1.4 on 2025-01-04 05:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_achievement_userachievement_userstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='user',
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='key',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='xp_reward',
        ),
        migrations.AddField(
            model_name='achievement',
            name='xp_threshold',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnlockedAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.achievement')),
                ('user_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_achievements', to='stats.userprogress')),
            ],
            options={
                'unique_together': {('user_progress', 'achievement')},
            },
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
