# Generated by Django 5.1.4 on 2024-12-30 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_level_exerciseattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_key', models.CharField(max_length=50)),
                ('correct_answer', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blanks', to='exercises.exercise')),
            ],
        ),
    ]
